Going to try with matplot lib

I used chatgpt to help me generate some of this initial code

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.colors as mcolors

Read in dataframes, and then make a list of dataframes so I can run through them all

In [ ]:
#election years
df_2005 = pd.read_csv('DC-migration-2005.csv')
df_2009 = pd.read_csv('DC-migration-2009.csv')
df_2013 = pd.read_csv('DC-migration-2013.csv')
df_2017 = pd.read_csv('DC-migration-2017.csv')
df_2021 = pd.read_csv('DC-migration-2021.csv')


#pre-election years for comparison

df_2015 = pd.read_csv('DC-migration-2015.csv')
df_2016 = pd.read_csv('DC-migration-2016.csv')
df_2018 = pd.read_csv('DC-migration-2018.csv')
df_2019 = pd.read_csv('DC-migration-2019.csv')

Drop the initial columns that were carried over from the indexes and messing up this data.

In [ ]:
df_2005 = df_2005.drop(columns=["Unnamed: 0"])
df_2009 = df_2009.drop(columns=["Unnamed: 0"])
df_2013 = df_2013.drop(columns=["Unnamed: 0"])
df_2017 = df_2017.drop(columns=["Unnamed: 0"])
df_2021 = df_2021.drop(columns=["Unnamed: 0"])

df_2015 = df_2015.drop(columns=["Unnamed: 0"])
df_2016 = df_2016.drop(columns=["Unnamed: 0"])
df_2018 = df_2018.drop(columns=["Unnamed: 0"])
df_2019 = df_2019.drop(columns=["Unnamed: 0"])

In [ ]:
df_2005.tail()

df_2015.tail()

Add in a state year column so in order to be able to loop through the dataframes

In [ ]:
df_2005['year'] = 2005
df_2009['year'] = 2009
df_2013['year'] = 2013
df_2017['year'] = 2017
df_2021['year'] = 2021

df_2015['year'] = 2015
df_2016['year'] = 2016
df_2018['year'] = 2018
df_2019['year'] = 2019

Forming a new dataframe with 2015, 2016, 2017 data

In [ ]:
df_2015_16_17_compare = pd.DataFrame()

df_2015_16_17_compare['state'] = df_2017['state'].copy()
df_2015_16_17_compare['pop_migrated_2015'] = df_2015['pop_migrated'].copy()
df_2015_16_17_compare['pop_migrated_2016'] = df_2016['pop_migrated'].copy()
df_2015_16_17_compare['pop_migrated_2017'] = df_2017['pop_migrated'].copy()

Make a new column averaging the non election years -- i.e. 2015 and 2016 (since census is early in year before election)

In [ ]:
df_2015_16_17_compare['15_16_avg'] = (df_2015_16_17_compare['pop_migrated_2015'] + df_2015_16_17_compare['pop_migrated_2016']) / 2

In [ ]:
df_2015_16_17_compare.head(30)

Make a new column with the percent change between 2016 and 2017 years

In [ ]:
df_2015_16_17_compare['pct_change_pre_post_election'] = (
    df_2015_16_17_compare['pop_migrated_2017'] - df_2015_16_17_compare['15_16_avg']
) / df_2015_16_17_compare["15_16_avg"] * 100

df_2015_16_17_compare.head()

Add back in the party info

In [ ]:
df_2015_16_17_compare['winning_party'] = df_2017['winning_party'] 
df_2015_16_17_compare['winner_percent_of_votes'] = df_2017['winner_percent_of_votes'] 

df_2015_16_17_compare.head()

Add a total column, so that I can see tota numbers migrating into D.C. in an election year and not in an election year.

In [ ]:
df_2015_16_17_compare.loc["Total"] = df_2015_16_17_compare.sum(numeric_only=True)

df_2015_16_17_compare.head()

In [ ]:
df_2015_16_17_compare.sort_values('pct_change_pre_post_election', ascending=False)

Forming a new dataframe with 2018 and 2019, and 2021 data (there is no 2018 instead of 2020 because no data in 2020 because of covid)

In [ ]:
df_2018_19_21_compare = pd.DataFrame()

df_2018_19_21_compare['state'] = df_2019['state'].copy()
df_2018_19_21_compare['pop_migrated_2018'] = df_2018['pop_migrated'].copy()
df_2018_19_21_compare['pop_migrated_2019'] = df_2019['pop_migrated'].copy()
df_2018_19_21_compare['pop_migrated_2021'] = df_2021['pop_migrated'].copy()

Make a column averaging 2018 and 2019

In [ ]:
df_2018_19_21_compare['18-19_avg'] = (df_2018_19_21_compare['pop_migrated_2018'] + df_2018_19_21_compare['pop_migrated_2019']) / 2

Add back in the party info

In [ ]:
df_2018_19_21_compare['winning_party'] = df_2021['winning_party'] 
df_2018_19_21_compare['winner_percent_of_votes'] = df_2021['winner_percent_of_votes'] 

df_2018_19_21_compare.head()

Percent change 2019 vs 2021 of migrants to DC from each state

In [ ]:
df_2018_19_21_compare['pct_change_pre_post_election'] = (
    df_2018_19_21_compare['pop_migrated_2021'] - df_2018_19_21_compare['18-19_avg']
) / df_2018_19_21_compare["18-19_avg"] * 100

df_2018_19_21_compare.head()

Add in a total column so that I can see tota numbers migrating into D.C. in an election year and not in an election year.

In [ ]:
df_2018_19_21_compare.loc["Total"] = df_2018_19_21_compare.sum(numeric_only=True)

df_2018_19_21_compare.head()

In [ ]:
df_2018_19_21_compare.sort_values('pct_change_pre_post_election', ascending=False)

In [22]:
df_2018_19_21_compare.head()

,state,pop_migrated_2018,pop_migrated_2019,pop_migrated_2021,18-19_avg,winning_party,winner_percent_of_votes,pct_change_pre_post_election
0,Alabama,174.0,462.0,342.0,318.0,REPUBLICAN,0.620316,7.547170
1,Alaska,0.0,338.0,196.0,169.0,REPUBLICAN,0.528331,15.976331
2,Arizona,204.0,291.0,674.0,247.5,DEMOCRAT,0.493647,172.323232
3,Arkansas,0.0,0.0,37.0,0.0,REPUBLICAN,0.623957,inf
4,California,3803.0,3437.0,3945.0,3620.0,DEMOCRAT,0.634839,8.977901

New method to see anomolies

In [34]:
df_2015_16_17_compare['avg_all years'] = (df_2005['pop_migrated'] + df_2009['pop_migrated'] + df_2013['pop_migrated'] + df_2021['pop_migrated'] + df_2015['pop_migrated'] + df_2016['pop_migrated'] + df_2018['pop_migrated'] + df_2019['pop_migrated']) / 8


df_2015_16_17_compare['anomoly'] = df_2015_16_17_compare['pop_migrated_2017'] / df_2015_16_17_compare['avg_all years']

In [25]:
df_2018_19_21_compare['avg_all years'] = (df_2005['pop_migrated'] + df_2009['pop_migrated'] + df_2013['pop_migrated'] + df_2017['pop_migrated'] + df_2015['pop_migrated'] + df_2016['pop_migrated'] + df_2018['pop_migrated'] + df_2019['pop_migrated']) / 8


df_2018_19_21_compare['anomoly'] = df_2018_19_21_compare['pop_migrated_2021'] / df_2018_19_21_compare['avg_all years']

Look at anomolies

In [31]:
df_2018_19_21_compare.sort_values('anomoly', ascending=False)

,state,pop_migrated_2018,pop_migrated_2019,pop_migrated_2021,18-19_avg,winning_party,winner_percent_of_votes,pct_change_pre_post_election,avg_all years,anomoly
15,Kansas,0.0,41.0,503.0,20.5,REPUBLICAN,0.562125,2353.658537,21.125,23.810651
7,Delaware,182.0,0.0,3560.0,91.0,DEMOCRAT,0.587430,3812.087912,293.875,12.113994
18,Maine,61.0,448.0,1028.0,254.5,DEMOCRAT,0.525256,303.929273,196.375,5.234882
44,Washington,387.0,852.0,1817.0,619.5,DEMOCRAT,0.579703,193.301049,348.625,5.211904
26,Nevada,36.0,0.0,431.0,18.0,DEMOCRAT,0.500568,2294.444444,91.875,4.691156
11,Idaho,0.0,28.0,93.0,14.0,REPUBLICAN,0.638376,564.285714,24.250,3.835052
34,Oklahoma,0.0,185.0,374.0,92.5,REPUBLICAN,0.653733,304.324324,99.500,3.758794
47,Wyoming,68.0,0.0,56.0,34.0,REPUBLICAN,0.694998,64.705882,15.625,3.584000
27,New Hampshire,130.0,49.0,266.0,89.5,DEMOCRAT,0.527078,197.206704,91.000,2.923077
35,Oregon,80.0,172.0,426.0,126.0,DEMOCRAT,0.564533,238.095238,153.250,2.779772
24,Montana,92.0,4.0,65.0,48.0,REPUBLICAN,0.569185,35.416667,27.875,2.331839
21,Minnesota,143.0,278.0,726.0,210.5,DEMOCRAT,0.523951,244.893112,312.625,2.322271
33,Ohio,1592.0,755.0,1610.0,1173.5,REPUBLICAN,0.532713,37.196421,745.375,2.159987
2,Arizona,204.0,291.0,674.0,247.5,DEMOCRAT,0.493647,172.323232,344.500,1.956459
45,West Virginia,294.0,324.0,568.0,309.0,REPUBLICAN,0.686316,83.818770,297.375,1.910046
14,Iowa,162.0,59.0,145.0,110.5,REPUBLICAN,0.528002,31.221719,81.375,1.781874
9,Georgia,647.0,1190.0,1662.0,918.5,DEMOCRAT,0.494731,80.947197,1022.250,1.625825
8,Florida,1789.0,1496.0,2581.0,1642.5,REPUBLICAN,0.512198,57.138508,1825.000,1.414247
28,New Jersey,2382.0,2758.0,2709.0,2570.0,DEMOCRAT,0.573342,5.408560,1923.375,1.408462
16,Kentucky,110.0,131.0,202.0,120.5,REPUBLICAN,0.620866,67.634855,153.250,1.318108
37,Rhode Island,87.0,138.0,366.0,112.5,DEMOCRAT,0.594762,225.333333,287.000,1.275261
0,Alabama,174.0,462.0,342.0,318.0,REPUBLICAN,0.620316,7.547170,268.500,1.273743
46,Wisconsin,346.0,362.0,307.0,354.0,DEMOCRAT,0.494495,-13.276836,247.125,1.242286
36,Pennsylvania,1617.0,1718.0,2237.0,1667.5,DEMOCRAT,0.500085,34.152924,1800.750,1.242260
6,Connecticut,262.0,1298.0,1102.0,780.0,DEMOCRAT,0.592607,41.282051,921.500,1.195876
4,California,3803.0,3437.0,3945.0,3620.0,DEMOCRAT,0.634839,8.977901,3348.125,1.178271
12,Illinois,1066.0,1361.0,1736.0,1213.5,DEMOCRAT,0.575416,43.057272,1499.750,1.157526
19,Massachusetts,1664.0,2383.0,2389.0,2023.5,DEMOCRAT,0.651230,18.062763,2098.250,1.138568
1,Alaska,0.0,338.0,196.0,169.0,REPUBLICAN,0.528331,15.976331,183.625,1.067393
40,Tennessee,690.0,991.0,663.0,840.5,REPUBLICAN,0.606603,-21.118382,634.875,1.044300
17,Louisiana,0.0,452.0,324.0,226.0,REPUBLICAN,0.584609,43.362832,328.875,0.985177
41,Texas,1036.0,2073.0,1498.0,1554.5,REPUBLICAN,0.520576,-3.634609,1583.500,0.946006
20,Michigan,486.0,758.0,607.0,622.0,DEMOCRAT,0.506208,-2.411576,660.625,0.918827
31,North Carolina,1026.0,1481.0,1330.0,1253.5,REPUBLICAN,0.499343,6.102912,1490.875,0.892094
30,New York,4642.0,4314.0,3658.0,4478.0,DEMOCRAT,0.603919,-18.311746,4413.375,0.828844
3,Arkansas,0.0,0.0,37.0,0.0,REPUBLICAN,0.623957,inf,51.750,0.714976
5,Colorado,336.0,870.0,261.0,603.0,DEMOCRAT,0.550111,-56.716418,548.750,0.475626
13,Indiana,146.0,427.0,159.0,286.5,REPUBLICAN,0.570212,-44.502618,424.375,0.374669
38,South Carolina,408.0,568.0,196.0,488.0,REPUBLICAN,0.550935,-59.836066,580.875,0.337422
23,Missouri,201.0,976.0,87.0,588.5,REPUBLICAN,0.567997,-85.216653,349.750,0.248749
22,Mississippi,146.0,265.0,29.0,205.5,REPUBLICAN,0.576030,-85.888078,141.250,0.205310
42,Utah,215.0,0.0,24.0,107.5,REPUBLICAN,0.581298,-77.674419,252.875,0.094909
43,Vermont,213.0,54.0,0.0,133.5,DEMOCRAT,0.654558,-100.000000,127.375,0.000000
10,Hawaii,124.0,0.0,0.0,62.0,DEMOCRAT,0.631494,-100.000000,106.000,0.000000
39,South Dakota,0.0,250.0,0.0,125.0,REPUBLICAN,0.617694,-100.000000,65.000,0.000000
32,North Dakota,0.0,0.0,0.0,0.0,REPUBLICAN,0.651140,NaN,11.000,0.000000
25,Nebraska,0.0,49.0,0.0,24.5,REPUBLICAN,0.582242,-100.000000,147.250,0.000000
29,New Mexico,0.0,466.0,0.0,233.0,DEMOCRAT,0.542893,-100.000000,167.000,0.000000
Total,NaN,27047.0,34552.0,40989.0,30799.5,NaN,27.582650,inf,NaN,NaN

In [35]:
df_2015_16_17_compare.sort_values('anomoly', ascending=False)

,state,pop_migrated_2015,pop_migrated_2016,pop_migrated_2017,15_16_avg,pct_change_pre_post_election,winning_party,winner_percent_of_votes,avg_all years,anomoly
11,Idaho,5.0,0.0,161.0,2.5,6340.000000,REPUBLICAN,0.592614,15.750,10.222222
43,Vermont,117.0,0.0,447.0,58.5,664.102564,DEMOCRAT,0.557227,71.500,6.251748
5,Colorado,433.0,531.0,1109.0,482.0,130.082988,DEMOCRAT,0.481570,442.750,2.504800
3,Arkansas,203.0,0.0,105.0,101.5,3.448276,REPUBLICAN,0.605741,43.250,2.427746
41,Texas,1314.0,2213.0,2858.0,1763.5,62.064077,REPUBLICAN,0.522347,1413.500,2.021931
13,Indiana,748.0,957.0,710.0,852.5,-16.715543,REPUBLICAN,0.569400,355.500,1.997187
16,Kentucky,275.0,233.0,285.0,254.0,12.204724,REPUBLICAN,0.625196,142.875,1.994751
12,Illinois,785.0,2418.0,2726.0,1601.5,70.215423,DEMOCRAT,0.558254,1376.000,1.981105
0,Alabama,359.0,140.0,494.0,249.5,97.995992,REPUBLICAN,0.620831,249.500,1.979960
42,Utah,177.0,249.0,384.0,213.0,80.281690,REPUBLICAN,0.455408,207.875,1.847264
40,Tennessee,873.0,452.0,1057.0,662.5,59.547170,REPUBLICAN,0.607220,585.625,1.804909
23,Missouri,141.0,566.0,466.0,353.5,31.824611,REPUBLICAN,0.567723,302.375,1.541133
2,Arizona,367.0,744.0,549.0,555.5,-1.170117,REPUBLICAN,0.486716,360.125,1.524471
17,Louisiana,392.0,197.0,461.0,294.5,56.536503,REPUBLICAN,0.580887,311.750,1.478749
29,New Mexico,40.0,1.0,206.0,20.5,904.878049,DEMOCRAT,0.482556,141.250,1.458407
9,Georgia,1013.0,1105.0,1507.0,1059.0,42.304060,REPUBLICAN,0.507713,1041.625,1.446778
28,New Jersey,1804.0,1494.0,2590.0,1649.0,57.064888,DEMOCRAT,0.554531,1938.250,1.336257
31,North Carolina,1501.0,1367.0,1867.0,1434.0,30.195258,REPUBLICAN,0.498281,1423.750,1.311326
19,Massachusetts,2876.0,1974.0,2669.0,2425.0,10.061856,DEMOCRAT,0.590501,2063.250,1.293590
20,Michigan,1308.0,922.0,808.0,1115.0,-27.533632,REPUBLICAN,0.474976,635.500,1.271440
6,Connecticut,1292.0,1225.0,1149.0,1258.5,-8.700834,DEMOCRAT,0.545663,915.625,1.254881
33,Ohio,1027.0,659.0,1026.0,843.0,21.708185,REPUBLICAN,0.516877,818.375,1.253704
22,Mississippi,338.0,224.0,157.0,281.0,-44.128114,REPUBLICAN,0.579410,125.250,1.253493
21,Minnesota,545.0,542.0,436.0,543.5,-19.779209,DEMOCRAT,0.464450,348.875,1.249731
30,New York,5133.0,4762.0,5238.0,4947.5,5.871652,DEMOCRAT,0.561361,4215.875,1.242447
4,California,4119.0,3908.0,3763.0,4013.5,-6.241435,DEMOCRAT,0.617264,3370.875,1.116327
37,Rhode Island,234.0,268.0,296.0,251.0,17.928287,DEMOCRAT,0.544066,295.750,1.000845
26,Nevada,68.0,356.0,128.0,212.0,-39.622642,DEMOCRAT,0.479178,129.750,0.986513
36,Pennsylvania,1999.0,2468.0,1824.0,2233.5,-18.334453,REPUBLICAN,0.485779,1852.375,0.984682
27,New Hampshire,47.0,168.0,88.0,107.5,-18.139535,DEMOCRAT,0.468263,113.250,0.777042
8,Florida,2731.0,2717.0,1182.0,2724.0,-56.607930,REPUBLICAN,0.490219,1999.875,0.591037
7,Delaware,252.0,278.0,375.0,265.0,41.509434,DEMOCRAT,0.533533,692.000,0.541908
32,North Dakota,0.0,83.0,5.0,41.5,-87.951807,REPUBLICAN,0.629556,10.375,0.481928
46,Wisconsin,514.0,242.0,115.0,378.0,-69.576720,REPUBLICAN,0.472182,271.125,0.424159
38,South Carolina,1806.0,382.0,235.0,1094.0,-78.519196,REPUBLICAN,0.549393,576.000,0.407986
18,Maine,258.0,118.0,122.0,188.0,-35.106383,DEMOCRAT,0.463452,309.625,0.394025
44,Washington,134.0,418.0,206.0,276.0,-25.362319,DEMOCRAT,0.525387,550.000,0.374545
10,Hawaii,52.0,103.0,29.0,77.5,-62.580645,DEMOCRAT,0.609808,102.375,0.283272
35,Oregon,157.0,125.0,37.0,141.0,-73.758865,DEMOCRAT,0.500719,201.875,0.183282
14,Iowa,135.0,218.0,17.0,176.5,-90.368272,REPUBLICAN,0.511621,97.375,0.174583
45,West Virginia,478.0,296.0,0.0,387.0,-100.000000,REPUBLICAN,0.686306,368.375,0.000000
24,Montana,0.0,17.0,0.0,8.5,-100.000000,REPUBLICAN,0.564662,36.000,0.000000
39,South Dakota,9.0,0.0,0.0,4.5,-100.000000,REPUBLICAN,0.615308,65.000,0.000000
34,Oklahoma,150.0,122.0,0.0,136.0,-100.000000,REPUBLICAN,0.653229,146.250,0.000000
25,Nebraska,674.0,190.0,0.0,432.0,-100.000000,REPUBLICAN,0.587474,147.250,0.000000
1,Alaska,235.0,77.0,0.0,156.0,-100.000000,REPUBLICAN,0.512815,208.125,0.000000
15,Kansas,33.0,0.0,0.0,16.5,-100.000000,REPUBLICAN,0.566546,84.000,0.000000
47,Wyoming,0.0,0.0,0.0,0.0,NaN,REPUBLICAN,0.673984,22.625,0.000000
Total,NaN,37151.0,35529.0,37887.0,36340.0,7259.628037,NaN,26.348198,NaN,NaN

Export

In [ ]:
df_2015_16_17_compare.to_csv('df_2015_16_17_compare.csv')
df_2018_19_21_compare.to_csv('df_2015_16_17_compare.csv')