In [1]:
import pandas as pd

import numpy as np

read in .csv

In [2]:
df_2021 = pd.read_csv('DC-migration-2021.csv')

I want to find some overall migration numbers for the narrative part of my story.

First, in 2021 as a sample year, total migration to DC:

Can see from original unparced data that total migration to DC is 57,746 +/- 5,874 in 2021.

Now I want to see how that figure compares to other states, adjusted per capita.

I want to take that original excel file and pull out the total migration from each state and compare to population.

Repeating parsing from the DC-migration-2021-ran.ipynb notebook

In [3]:
df = pd.read_excel('ORIGINAL DATA State_to_State_Migrations_Table_2021.xls')

df = df.iloc[np.r_[4:43, 44:77]] #drop top and bottom outside of actual chart in the excel file

df = df.dropna(how="all") #drop all rows with all na values

Rename columns

In [4]:

#for the first column

df.rename(columns={'Table with row headers in column A, L, W, AH, AS, BD, BO, BZ, CK, CV, and DG, and column headers in rows 6 through 8 and 45 through 47.': '0'}, inplace=True)

#for the rest of the columns:

for col in df.columns[1:130]:  # 2–129 (0-based index, so skip first col)
    if str(col).startswith("Unnamed:"):
        df.rename(columns={col: str(col).replace("Unnamed: ", "")}, inplace=True)

df.head()

,0,1,2,3,4,5,6,7,8,9,...,120,121,122,123,124,125,126,127,128,129
4,Current residence in,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN,NaN,...,NaN,Current residence in,Abroad 1 year ago,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN,Alabama,...,NaN,NaN,Total,NaN,Puerto Rico,NaN,U.S. Island Area,NaN,Foreign Country,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,...,MOE,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States2,328464538,34090,286552923,190336,32577121,167671,7859837,75123,104481,...,6515,United States2,1474657,34636,54669,7470,19587,4066,1400401,33711
10,Alabama,4989797,4341,4392571,25089,468964,23356,115641,10300,NaN,...,216,Alabama,12621,2388,534,436,29,47,12058,2400

Drop the whole end of the dataframe, as I wont be needing for this

In [5]:
df = df.loc[:, :'8']

Preserve NA values as 0s

In [6]:
df.iloc[3:] = df.iloc[3:].fillna('0')

df.head()

,0,1,2,3,4,5,6,7,8
4,Current residence in,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States2,328464538,34090,286552923,190336,32577121,167671,7859837,75123
10,Alabama,4989797,4341,4392571,25089,468964,23356,115641,10300

Rename columns and drop columns I don't need.
I want to keep only three columns: statename, Population 1 year and over, and Different state of residence 1 year ago -- total.
I can calucate the rest from there.

In [7]:
#first, dealing with columns B-G/1-6)

column_0_name = 'state'

column_1_name = 'population 1 year and over (estimate)'
column_2_name = 'population 1 year and over (moe)'

column_5_name = 'Same state of residence 1 year ago (estimate)'
column_6_name = 'Same state of residence 1 year ago (moe)'

column_7_name = 'Different state of residence 1 year ago (estimate)'
column_8_name = 'Different state of residence 1 year ago (moe)'

df_clean = df.rename(columns ={
    '0': column_0_name,
    '1': column_1_name,
    '2': column_2_name,
    '5': column_5_name,
    '6': column_6_name,
    '7': column_7_name,
    '8': column_8_name})

df = df_clean

df.head()

,state,population 1 year and over (estimate),population 1 year and over (moe),3,4,Same state of residence 1 year ago (estimate),Same state of residence 1 year ago (moe),Different state of residence 1 year ago (estimate),Different state of residence 1 year ago (moe)
4,Current residence in,Population 1 year and over,NaN,Same house 1 year ago,NaN,Same state of residence 1 year ago,NaN,Different state of residence 1 year ago,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,NaN
6,NaN,Estimate,MOE,Estimate,MOE,Estimate,MOE,Estimate,MOE
8,United States2,328464538,34090,286552923,190336,32577121,167671,7859837,75123
10,Alabama,4989797,4341,4392571,25089,468964,23356,115641,10300

In [8]:


#drop columns I dont need (same house as 1 year ago estimate and MOE columns)
df.drop(['3', '4'], axis=1, inplace=True)

Delete subtitle rows

In [9]:
df = df.iloc[3:]

df.head()

,state,population 1 year and over (estimate),population 1 year and over (moe),Same state of residence 1 year ago (estimate),Same state of residence 1 year ago (moe),Different state of residence 1 year ago (estimate),Different state of residence 1 year ago (moe)
8,United States2,328464538,34090,32577121,167671,7859837,75123
10,Alabama,4989797,4341,468964,23356,115641,10300
11,Alaska,723949,1517,63611,6501,31378,3888
12,Arizona,7202745,5156,759450,24263,264948,14419
13,Arkansas,2990311,2937,312848,15129,76108,8024

In [10]:
df['Different state of residence 1 year ago (estimate)'] = pd.to_numeric(df['Different state of residence 1 year ago (estimate)'], errors='coerce')

df['population 1 year and over (estimate)'] = pd.to_numeric(df['population 1 year and over (estimate)'], errors='coerce')

df['new_people_adj'] = df['Different state of residence 1 year ago (estimate)'] / df['population 1 year and over (estimate)']

df.head()

,state,population 1 year and over (estimate),population 1 year and over (moe),Same state of residence 1 year ago (estimate),Same state of residence 1 year ago (moe),Different state of residence 1 year ago (estimate),Different state of residence 1 year ago (moe),new_people_adj
8,United States2,328464538.0,34090,32577121,167671,7859837.0,75123,0.023929
10,Alabama,4989797.0,4341,468964,23356,115641.0,10300,0.023175
11,Alaska,723949.0,1517,63611,6501,31378.0,3888,0.043343
12,Arizona,7202745.0,5156,759450,24263,264948.0,14419,0.036784
13,Arkansas,2990311.0,2937,312848,15129,76108.0,8024,0.025452

In [15]:
df.sort_values('new_people_adj', ascending=False)

,state,population 1 year and over (estimate),population 1 year and over (moe),Same state of residence 1 year ago (estimate),Same state of residence 1 year ago (moe),Different state of residence 1 year ago (estimate),Different state of residence 1 year ago (moe),new_people_adj
19,District of Columbia,661026.0,1835,68606,7109,57746.0,5874,0.087358
24,Idaho,1879719.0,2400,176458,11576,96388.0,9806,0.051278
23,Hawaii,1426298.0,2455,110790,9317,71626.0,8474,0.050218
68,Vermont,641007.0,929,42454,4180,31809.0,3854,0.049623
55,North Dakota,764638.0,1475,83572,7158,37844.0,5480,0.049493
74,Wyoming,573476.0,1211,63128,6111,27281.0,4320,0.047571
16,Colorado,5757628.0,4091,686892,20293,250031.0,17084,0.043426
11,Alaska,723949.0,1517,63611,6501,31378.0,3888,0.043343
18,Delaware,994669.0,1764,58180,5692,42551.0,4342,0.042779
48,Nevada,3111722.0,3366,305571,18198,132648.0,11663,0.042628
41,Montana,1093888.0,1329,100380,7474,44531.0,5330,0.040709
61,Rhode Island,1085539.0,1975,77691,8236,43266.0,4692,0.039857
49,New Hampshire,1377638.0,1710,97263,8285,53245.0,5800,0.038649
62,South Carolina,5142137.0,4196,484535,19587,196200.0,11924,0.038155
12,Arizona,7202745.0,5156,759450,24263,264948.0,14419,0.036784
29,Kansas,2900594.0,2687,323036,14539,102319.0,9863,0.035275
51,New Mexico,2092251.0,2945,188495,12055,68019.0,7525,0.032510
54,North Carolina,10446881.0,5346,1032016,31433,336681.0,16849,0.032228
65,Tennessee,6899165.0,4617,701333,22674,220591.0,14903,0.031974
32,Maine,1360264.0,1424,111418,7447,43492.0,4855,0.031973
69,Virginia,8557020.0,4817,855269,26354,272693.0,12741,0.031868
59,Oregon,4207387.0,3683,458434,18455,133935.0,9142,0.031833
20,Florida,21590684.0,8058,2206566,41666,674740.0,25002,0.031251
63,South Dakota,884616.0,1584,95407,7171,27528.0,3650,0.031119
67,Utah,3295561.0,3308,359628,15733,101051.0,8401,0.030663
17,Connecticut,3571470.0,3191,279328,13726,106618.0,8523,0.029853
71,Washington,7657350.0,4731,909338,26736,225306.0,12843,0.029423
22,Georgia,10688429.0,6334,1107180,34938,302512.0,17711,0.028303
57,Oklahoma,3943443.0,2733,475441,17079,108288.0,7791,0.027460
40,Missouri,6102443.0,4216,635797,21055,165921.0,9843,0.027189
34,Maryland,6099715.0,4217,519574,25291,160016.0,10653,0.026233
13,Arkansas,2990311.0,2937,312848,15129,76108.0,8024,0.025452
72,West Virginia,1767792.0,1989,137757,9831,43801.0,6531,0.024777
28,Iowa,3159672.0,2419,347372,13477,77245.0,6177,0.024447
30,Kentucky,4460646.0,2878,463451,18318,107693.0,6224,0.024143
8,United States2,328464538.0,34090,32577121,167671,7859837.0,75123,0.023929
26,Indiana,6729771.0,4323,714384,23581,156417.0,11930,0.023243
10,Alabama,4989797.0,4341,468964,23356,115641.0,10300,0.023175
35,Massachusetts,6916314.0,4173,663154,18384,158311.0,7554,0.022890
47,Nebraska,1939700.0,1981,208977,8549,43287.0,5163,0.022316
50,New Jersey,9174117.0,4777,723937,24913,195828.0,12159,0.021346
73,Wisconsin,5838954.0,3227,578787,17247,122742.0,7724,0.021021
38,Mississippi,2919574.0,3069,241171,15519,59759.0,6266,0.020468
60,Pennsylvania,12842522.0,5067,1078336,27367,261831.0,13241,0.020388
66,Texas,29170380.0,12760,3315313,62222,591395.0,26127,0.020274
31,Louisiana,4571302.0,4582,483769,18398,81944.0,8435,0.017926
37,Minnesota,5645866.0,3318,606582,17333,93286.0,6975,0.016523
56,Ohio,11660200.0,5489,1228277,27914,184477.0,11210,0.015821
25,Illinois,12544435.0,5532,1200753,28559,195177.0,9929,0.015559
53,New York,19626300.0,8200,1666707,37802,287249.0,11439,0.014636
36,Michigan,9950336.0,4442,950370,25147,143042.0,9088,0.014376
14,California,38833197.0,12214,3749371,49440,433402.0,16802,0.011161
76,Puerto Rico,3248011.0,2728,177594,12122,27380.0,3989,0.008430
44,0,0.0,0,0,0,NaN,0,NaN
45,0,NaN,MOE,Estimate,MOE,NaN,MOE,NaN